FROM ghcr.io/admenergy/workspace:latest

ARG PROJECT_NAME=next-common
ENV PROJECT_NAME=$PROJECT_NAME
RUN test -n "$PROJECT_NAME" || (echo "Docker build error: PROJECT_NAME build arg is required" && exit 1) \
	&& mkdir -p /workspace/$PROJECT_NAME \
	&& chown vscode:vscode /workspace /workspace/$PROJECT_NAME

COPY .devcontainer/post-*.sh /var/
ENV DEBIAN_FRONTEND=dialog
RUN /finalize
